language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
    - '${NVM_PATH}_modules'
install:
  - yarn
  - cd functions && yarn && cd ..
script:
  - yarn lint
  - echo "Building..."
  - 'if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi'
  - 'if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi'
before_deploy:
  - echo "Deploying!"
deploy:
  - provider: firebase
    skip_cleanup: true
    'on':
      branch: master
    project: hoverboard-9bb68
    token:
      secure: "L8TTCI5G+RkzNBVDMhfTFnc1CTvKWbtsj08ka9fOoPsWhoMf7QSuGBwhP0/turTUUosiQ201+KnIkb12XgZemkFoiIa++mN55yRBZZZ6gOpFI9/avq2ms8tmE6YvyNZ9vOLIBZ/dMEmZt7j6AqNtpH3PTHkuucUnrhuQfQDQ6ECvbVcTpnft21SPg6FeILf96m5cKhNLrlMaeFNogtyeZM8IvGqEfiw/cW3D3nNpYdEWsrvm3W+5zrpa7CmaDhjHgVavx4SXTSb7bZmpTx242sBHCer/THWjdW/x6Bw8TcIbYG9rydKxdpjR1L6BQzlWv4txOC5etEPS2z1jB7sHz84/2r7Dz5K0dRJ10lUXW71y5QzBSv9f8FR1rooudPyszmN1P3TfOi/LoWtEZXtkk6rWm+f/8Ky2oPW6ztO93RNUM8tO9wW7zDM4msq2qS7UF+5QJUdZVDMuNyjlXoRlirfe4duiZ4qindXrUFojPSIUmFQKMdvPdjZuY0hIyfQQUv1rolWvxu4OSaGVlY7Ibc6Lo7E8Z+X0DG/cPMrhnTArlzuLyB1D7/+dbLUuUmlHSmLnO7BhGaJNMWUI3MalmEYBB28N1yLwxkkMyjmzeHfkT1pz0ud2wA9ImF/Q3DoR7EtKxuSnhcC7hE+JJafPmEZTo9kDKi9las+sSTYC7IM="
after_deploy:
  - yarn firestore:init


